# Generated by Django 5.2.5 on 2025-08-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_attendance_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
